secret_key = SECRET_KEY = "B18u$=r36621a*%"
rootPath = r"./Model"
Resumes_File_Path = "./ResumeProcess/saved_resume_files"
jd_File_Path = "./ResumeProcess/saved_jd_files"
upload_folder =  "./ResumeProcess"